; audio_data.s — SPC700 driver binary + audio data
; This file will be regenerated by exportgss.py when real audio is composed.
; For now it contains a minimal placeholder so the ROM builds.

.include "macros.s"

.export SpcImage, SpcImageSize, SpcEntryAddr

; ============================================================================
; AUDIODATA segment — lives in ROM bank 1 ($018000-$01FFFF)
; ============================================================================

.segment "AUDIODATA"

; SPC700 driver binary (placeholder: minimal program that loops forever)
; Real data: .incbin "spc700.bin"
; For now: a tiny SPC700 program at ARAM $0200 that clears APU ports and spins
SpcImage:
    ; SPC700 opcodes (not 65816!):
    ;   $E4 $F4 = MOV A, $F4      (read APUIO0)
    ;   $64 $F4 = MOV $F4, A      (clear APUIO0 — echo back)
    ;   $64 $F5 = MOV $F5, A      (clear APUIO1)
    ;   $64 $F6 = MOV $F6, A      (clear APUIO2)
    ;   $64 $F7 = MOV $F7, A      (clear APUIO3)
    ;   $2F $F7 = BRA -9          (loop back to start)
    .byte $E4, $F4          ; MOV A, $F4    ; Read port 0
    .byte $C4, $F4          ; MOV $F4, A    ; Echo back (acknowledge)
    .byte $C4, $F5          ; MOV $F5, A    ; Clear port 1
    .byte $C4, $F6          ; MOV $F6, A    ; Clear port 2
    .byte $C4, $F7          ; MOV $F7, A    ; Clear port 3
    .byte $2F, $F5          ; BRA -11       ; Loop to start
SpcImageEnd:

; Size of SPC image (used by SpcBootApu)
.segment "CODE"
SpcImageSize:   .word SpcImageEnd - SpcImage
SpcEntryAddr:   .word $0200             ; ARAM entry point
